MACRO(ADD_LIB_TESTS LibName Headers Tests Deps)
	set(_headers ${Headers})
	list(TRANSFORM _headers PREPEND include/${LibName}/ )

	set(_tests ${Tests})
	set(_deps ${Deps} )

	if (DEFINED _tests)
		list(LENGTH _tests _TestsLength)
	endif ()
	if (_TestsLength)
		list(TRANSFORM _tests PREPEND tests/)
		add_executable(test_${LibName} ${_tests} ${_headers})
		foreach (_dep ${_deps})
			get_filename_component(deplibname ${_dep} NAME)
			FETCH_DEPENDENCY(${deplibname})
			target_link_libraries(test_${LibName} PRIVATE ${deplibname})
		endforeach ()
		target_link_libraries(test_${LibName} ${LibName})
		target_include_directories(test_${LibName} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/tests)
	endif ()
ENDMACRO()

MACRO(ADD_LIB_GUITESTS LibName Headers Tests Deps)
	set(_headers ${Headers})
	list(TRANSFORM _headers PREPEND include/${LibName}/ )

	set(_tests ${Tests})
	set(_deps ${Deps} )
	if (DEFINED _tests)
		list(LENGTH _tests _TestsLength)
	endif ()

	if (DEFINED _deps)
		list(TRANSFORM _deps PREPEND ${LIB_BASE_PATH})
		set(_depsc ${_deps})
		list(TRANSFORM _depsc APPEND /include)
	endif()

	if (_TestsLength)
		list(TRANSFORM _tests PREPEND tests/)
		if(APPLE)
			list(APPEND _tests ${LIB_BASE_PATH}/level0/guishell/src/apple/appdelegate.h)
			list(APPEND _tests ${LIB_BASE_PATH}/level0/guishell/src/apple/appdelegate.m)
			list(APPEND _tests ${LIB_BASE_PATH}/level0/guishell/src/apple/macresources/MainMenu.nib)
		endif()
		add_executable(${LibName}_tests WIN32 MACOSX_BUNDLE ${_tests} ${_headers})
		target_link_libraries(${LibName}_tests ${LibName} core guishell)
		foreach (_dep ${_deps})
			get_filename_component(deplibname ${_dep} NAME)
			target_link_libraries(${LibName}_tests ${deplibname})
		endforeach ()

		target_include_directories(${LibName}_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/tests)
		target_include_directories(${LibName}_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)
		target_include_directories(${LibName}_tests PRIVATE ${_depsc})

		if(APPLE)
			set_target_properties(${LibName}_tests PROPERTIES
					MACOSX_BUNDLE_GUI_IDENTIFIER com.wryd.${LibName}_tests
					MACOSX_BUNDLE_INFO_PLIST ${LIB_BASE_PATH}/level0/guishell/src/apple/macresources/Info.plist.in
					RESOURCE ${LIB_BASE_PATH}/level0/guishell/src/apple/macresources/MainMenu.nib
					)
		endif()
	endif ()
ENDMACRO()